version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '80:3000'
    links:
      - api
    restart: always
    networks:
      - sportlive-networks
    environment:
      - TZ=Asia/Hong_Kong
  api:
    restart: always
    build: ./api
    command: sh -c "npm install && npm run start"
    working_dir: /api
    ports: 
      - '1001:3000'
    volumes:
      - ./api:/api
    networks:
      - sportlive-networks
    environment:
      - TZ=Asia/Hong_Kong

networks:
  sportlive-networks:
    driver: bridge
