version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '80:3000'
    links:
      - api
    restart: always
    networks:
      - sportlive-networks
    environment:
      - TZ=Asia/Hong_Kong
  api:
    restart: always
    build: ./api
    command: sh -c "npm install && npm run start"
    working_dir: /api
    ports: 
      - '1001:3000'
    volumes:
      - ./api:/api
    networks:
      - sportlive-networks
    environment:
      - TZ=Asia/Hong_Kong
    depends_on:
      - redis
  redis:
    image: redis:4.0-alpine
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    networks:
      - sportlive-networks
    ports:
      - '6379'
    command: redis-server /etc/redis/redis.conf
    container_name: redis
    hostname: redis

networks:
  sportlive-networks:
    driver: bridge
